project_id = "qmxuisekohvhybydzbvo"

[functions]
enabled = true

[functions.chat-bot-response]
verify_jwt = false

[functions.matchmaking]
verify_jwt = false

[functions.matchmaking]
verify_jwt = true