project_id = "qmxuisekohvhybydzbvo"

[functions]
enabled = true

[functions.chat-bot-response]
verify_jwt = true

[functions.chess-coach]
verify_jwt = true

[functions.matchmaking]
verify_jwt = true

[functions.create-guest-session]
verify_jwt = false

[functions.join-game-invite]
verify_jwt = false

[functions.fetch-reddit-posts]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
